#!/usr/bin/env python3
"""Turn one frame of training/out/final/test_vectors.npz into a C header.

The firmware runs this frame through its own DSP at boot and compares the
result with what features.py produced. It is a small check -- one frame, not a
whole window -- but it is the one that catches the mistakes that matter: a
scaled FFT, the wrong FFT sign, bit-reversed output, a Hann divided by 64
instead of 63. Each of those changes every value in the column.

Regenerate whenever features.py or the exported constants change:

    python tools/gen_selftest.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

REPO = Path(__file__).resolve().parent.parent
DEFAULT_VECTORS = REPO / "training" / "out" / "final" / "test_vectors.npz"
DEFAULT_OUT = REPO / "firmware" / "radar_infer" / "main" / "radar_selftest_data.h"


def c_array(values, per_line: int, fmt) -> str:
    out = []
    for i in range(0, len(values), per_line):
        out.append("\t" + " ".join(fmt(v) for v in values[i : i + per_line]))
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--vectors", type=Path, default=DEFAULT_VECTORS)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--window", type=int, default=0, help="which test window")
    ap.add_argument("--frame", type=int, default=0, help="which frame inside it")
    args = ap.parse_args()

    d = np.load(args.vectors, allow_pickle=True)
    w, f = args.window, args.frame

    real = d["raw_real"][w, f]          # (64 sweeps, 22 range)
    imag = d["raw_imag"][w, f]
    expected_db = d["spec_db"][w, f]    # (64,)
    expected_q = d["input_int8"][w, f]  # (64,)
    name = str(d["names"][w])

    # Interleave as the firmware's radar_sample_t: sweep-major, {real, imag}.
    samples = np.empty(real.size * 2, dtype=np.int16)
    samples[0::2] = real.reshape(-1)
    samples[1::2] = imag.reshape(-1)

    header = f"""/* Generated by tools/gen_selftest.py -- do not edit.
 *
 * Frame {f} of test window {w} ({name}), straight from
 * training/out/final/test_vectors.npz, with the column features.py computes
 * from it.
 */
#pragma once

#include <stdint.h>

/* {real.shape[0]} sweeps x {real.shape[1]} range points, interleaved real, imag. */
static const int16_t radar_selftest_frame[] = {{
{c_array(samples.tolist(), 16, lambda v: f"{v},")}
}};

/* features.py frame_column_db() for that frame, dB. */
static const float radar_selftest_expected_db[] = {{
{c_array(expected_db.tolist(), 6, lambda v: f"{v:.6f}f,")}
}};

/* ... and after normalise() + int8 quantisation. These must match exactly. */
static const int8_t radar_selftest_expected_q[] = {{
{c_array(expected_q.tolist(), 16, lambda v: f"{v},")}
}};
"""

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(header)

    print(f"{args.out.relative_to(REPO)}: frame {f} of window {w} ({name})")
    print(f"  {samples.size} int16 samples, {expected_db.size} expected dB values")
    print(f"  dB range {expected_db.min():.3f} .. {expected_db.max():.3f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
